# Generated by Django 4.2.4 on 2023-08-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_price_weeklycontrol_purchase_priceproductsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
