# Generated by Django 4.2.4 on 2024-02-20 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_unit_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='weekly_control',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.weeklycontrol'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('supplier', 'reference_day', 'weekly_control'), name='unique_daily_supplier_transaction'),
        ),
    ]
