# Generated by Django 4.2.4 on 2023-08-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_price_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reference_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
