# Generated by Django 4.2.4 on 2024-04-28 23:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('product', '0004_purchase_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='is_closed',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
                ('weekly_control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.weeklycontrol')),
            ],
            options={
                'verbose_name': 'Supplier payment',
                'verbose_name_plural': 'Supplier payments',
                'db_table': 'supplier_payment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierpayment',
            constraint=models.UniqueConstraint(fields=('supplier', 'weekly_control'), name='unique_weekly_supplier_payment'),
        ),
    ]
