# Generated by Django 4.2.4 on 2024-04-29 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_purchase_created_by_remove_purchase_is_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierpayment',
            name='weekly_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.weeklycontrol'),
        ),
    ]
