# Generated by Django 4.2.4 on 2024-04-30 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('product', '0006_alter_supplierpayment_weekly_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyControlEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RECORD', 'Registro'), ('PAYMENT', 'Pagamento'), ('PRICE', 'Preço')], max_length=7)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.supplier')),
                ('weekly_control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.weeklycontrol')),
            ],
            options={
                'verbose_name': 'Weekly control event',
                'verbose_name_plural': 'Weekly control events',
                'db_table': 'weekly_control_event',
                'ordering': ['created_at'],
            },
        ),
    ]
