# Generated by Django 4.2.4 on 2024-05-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_weeklycontrolevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontrolevent',
            name='new_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='weeklycontrolevent',
            name='old_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='weeklycontrolevent',
            name='reference_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklycontrolevent',
            name='type',
            field=models.CharField(choices=[('RECORD', 'Registro'), ('PAYMENT', 'Pagamento'), ('PRICE', 'Preço'), ('MANUAL', 'Manual')], max_length=7),
        ),
    ]
