# Generated by Django 4.2.4 on 2024-05-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_weeklycontrolevent_new_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklycontrolevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Weekly control event', 'verbose_name_plural': 'Weekly control events'},
        ),
    ]
